title: Klaxon Site Monitor
description: >- 
   Klaxon enables reporters and editors to monitor scores of sites and files on the web for newsworthy changes. 
   Get email and Slack notifications when something changes. Provide an optional CSS selector to only monitor 
   portions of a page you are interested in. 
type: object
documents: []
properties:
  site:
    title: Site
    type: string
    format: uri
    description: 
  selector: 
    title: Selector
    type: string
    description: CSS Selector on the page you would like to monitor.
required:
  - site
  - selector
eventOptions:
  name: site
  events:
    - hourly
    - daily
    - weekly
