title: Klaxon Site Monitor
description: >- 
   Klaxon enables reporters and editors to monitor scores of sites and files on the web for newsworthy changes. 
   Get email notifications when something changes. Provide an optional CSS selector to only monitor 
   portions of a page you are interested in. To get started, copy the bookmarklet [Add to Klaxon](javascript:(function(){document.body.appendChild(document.createElement('script')).src='https://documentcloud-klaxon.s3.amazonaws.com/inject.js';})();) to your bookmarks, 
   visit a page you are looking to monitor, and then click on the bookmark to activate Klaxon. 
type: object
properties:
  site:
    title: Site
    type: string
    format: uri
  selector: 
    title: Selector
    type: string
    description: CSS Selector on the page you would like to monitor.
  slack_webhook:
    title: Slack Webhook
    type: string
    format: uri
    description: Enter a slack webhook to enable Slack notifications
required:
  - site
  - selector
categories:
  - monitor
eventOptions:
  name: site
  events:
    - hourly
    - daily
    - weekly
