title: Klaxon Site Monitor
description: >- 
   Klaxon enables reporters and editors to monitor scores of sites and files on the web for newsworthy changes. 
   Get email notifications when something changes. Provide an optional CSS selector to only monitor 
   portions of a page you are interested in. To get started, [copy this bookmarklet] to your bookmarks, 
   visit a page you are looking to monitor, and then click on the bookmark to activate Klaxon. 
type: object
properties:
  site:
    title: Site
    type: string
    format: uri
  selector: 
    title: Selector
    type: string
    description: CSS Selector on the page you would like to monitor.
required:
  - site
  - selector
eventOptions:
  name: site
  events:
    - hourly
    - daily
    - weekly
