
name: Run Add-On
on: repository_dispatch

jobs:
  Run-Add-On:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@v1
    with: 
      timeout: 15
    secrets: 
     token: ${{ secrets.SAVEPAGENOW_SECRET_KEY }}
     key: ${{ secrets.SAVEPAGENOW_ACCESS_KEY }}
